projecttodoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls'))
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/home/', views.home, name='home'),
    path('authenticate-user/', views.authenticate_user, name='authenticate'),
    path('create-account/', views.create_account, name='create-account'),
    path('save-account/', views.save_account, name='save-account'),
    path('<int:user_id>/create-todo/', views.create_todo, name='create-todo'),
    path('<int:user_id>/<int:task_id>/delete/', views.delete_task, name='delete-task'),
    path('<int:user_id>/<int:task_id>/completed', views.mark_as_completed, name='completed'),
    path('<int:user_id>/delete-completed/', views.delete_completed, name='delete-completed'),
    path('<int:user_id>/<str:filter_name>/active-task/', views.filter, name='filter')
]

todo/models.py
from django.db import models

class User(models.Model):
  name = models.CharField(max_length=100)
  password = models.CharField(max_length=100)
  
  def __str__(self):
    return self.name



class Todo(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  text = models.CharField(max_length=200)
  is_completed = models.BooleanField(default=False)
  
  def __str__(self):
    return self.text

todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import User, Todo

def index(request):
  return render(request, 'todo/index.html')



def home(request, user_id): 
  user = User.objects.get(pk=user_id)
  todo_list = user.todo_set.all().order_by('id')
  
  
  context = {
    'user': user,
    'todo_list': todo_list,
    'uncompleted_task': len(todo_list.filter(is_completed=False))
  }
  
  return render(request, 'todo/home.html', context)



def credentials_are_incorrect(request):
  context = {
      'log_in_error_message': 'The username or password is incorrect!',
      'username': request.POST['username'],
      'password': request.POST['password']
    }
  
  return render(request, 'todo/index.html', context)



def authenticate_user(request):
  try:
    users = User.objects.get(name=request.POST['username'], password=request.POST['password'])
  except User.DoesNotExist:
    return credentials_are_incorrect(request)
  
  return HttpResponseRedirect(reverse('todo:home', args=(users.id,)))



def create_account(request):  
  return render(request, 'todo/create-account.html')



def save_user(request):
  new_user = User(name=request.POST['username'], password=request.POST['password'])
  new_user.save()
  
  return HttpResponseRedirect(reverse('todo:home', args=(new_user.id,)))



def save_account(request):  
  try:
    User.objects.get(name=request.POST['username'])
  except User.DoesNotExist:
    return save_user(request)

  context = {
    'username_error_message': 'Username already existed!',
    'to_create_account': True,
    'username': request.POST['username'],
    'password': request.POST['password']
  }
  return render(request, 'todo/create-account.html', context)



def create_todo(request, user_id):
  task =  request.POST['todoText'].lower()
  user = User.objects.get(pk=user_id)
  todo_list = user.todo_set.all()
  task_is_on_the_list = len(todo_list.filter(text=task)) >= 1
  
  context = {
      'user': user,
      'todo_list': todo_list,
      'uncompleted_task': len([not todo.is_completed for todo in todo_list]),
    }
  
  if task_is_on_the_list:
    context['todo_error_message'] = 'Task is already on the list!'
    return render(request, 'todo/home.html', context)
  else:
    new_task = user.todo_set.create(text=task)
    new_task.save()
    
    return HttpResponseRedirect(reverse('todo:home', args=(user_id,)))



def delete_task(request, user_id, task_id):
  user = User.objects.get(pk=user_id)
  task_list = user.todo_set.get(pk=task_id)
  task_list.delete()
  
  return HttpResponseRedirect(reverse('todo:home', args=(user_id,)))



def mark_as_completed(request, user_id, task_id):
  user = User.objects.get(pk=user_id)
  task = user.todo_set.get(pk=task_id)
  task.is_completed = not task.is_completed
  task.save() 
  
  return HttpResponseRedirect(reverse('todo:home', args=(user_id,)))



def delete_completed(request, user_id):
  user = User.objects.get(pk=user_id)
  
  try:
    completed_task = user.todo_set.filter(is_completed=True)
  except (KeyError, Todo.DoesNotExist):
    return HttpResponseRedirect(reverse('todo:home', args=(user_id,)))
  
  completed_task.delete()
  return HttpResponseRedirect(reverse('todo:home', args=(user_id,)))



def filter(request, user_id, filter_name):
  user = User.objects.get(pk=user_id)
  
  is_completed_only = filter_name == 'completed'
  todo_list = user.todo_set.filter(is_completed=is_completed_only).order_by('id')
  uncompleted_task = user.todo_set.filter(is_completed=False)
  
  context = {
    'user': user,
    'todo_list': todo_list,
    'uncompleted_task': len(uncompleted_task)
  }
  
  return render(request, 'todo/home.html', context)

templates/todo/create-account.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo</title>

    <style>
      * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
      }

      body {
        font-family: "Quicksand", sans-serif;
      }

      button {
        font-family: inherit;
      }

      .container {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
      }

      .card {
        padding: 1.5em;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.142);
        border-radius: 10px;
        margin: 0 1rem;
        width: 100%;
        max-width: 400px;
      }

      .card__title {
        text-align: center;
        margin-bottom: 1rem;
      }

      .form-label {
        font-size: 1.2rem;
        font-weight: 600;
        margin-bottom: 0.2rem;
        display: block;
      }

      .form-input-field {
        width: 100%;
        height: 30px;
        padding: 0 0.5em;
        font-size: 1.2rem;
      }

      .btn-login {
        background-color: #25273c;
        color: white;
        font-weight: 600;
        width: 100%;
        font-size: 1.5rem;
        padding: 0.5em;
        border: 1px solid #25273c;
        border-radius: 5px;
        cursor: pointer;
      }

      .btn-create {
        background-color: #3a7bfd;
        color: white;
        text-align: center;
        display: inline-block;
        text-decoration: none;
        padding: 0.5em 1em;
        margin-top: 1rem;
        font-size: 1.3rem;
        font-weight: 600;
        color: #ffffff;
        border-radius: 5px;
        border: none;
      }

      .text-center {
        text-align: center;
      }

      .mb-1 {
        margin-bottom: 1rem;
      }

      .error-message {
        color: #ff0000;
        margin-top: 0.5rem;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="card">
        <form action="{% url 'todo:save-account' %}" method="post">
          {% csrf_token %}
          <p class="error-message">{{ log_in_error_message }}</p>

          <div class="mb-1">
            <label class="form-label" for="username">Username</label>
            <input class="form-input-field" type="text" name="username" id="username" value="{{ username }}" required />
            <p class="error-message"> {{ username_error_message }} </p>
          </div>
          <div>
            <label class="form-label" for="password">Password</label>
            <input class="form-input-field mb-1" type="password" name="password" id="password" value="{{ password }}" required />
          </div>

          <div class="text-center">
            <button class="btn-create" type="submit">Create new account</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

templates/todo/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600;700&display=swap" rel="stylesheet" />
    <title>Todo - Home</title>
  </head>
  <style>
    * {
      padding: 0;
      margin: 0;
      box-sizing: border-box;
    }

    body {
      font-family: "Quicksand", sans-serif;
      background-color: #161722;
    }

    .container {
      display: flex;
      justify-content: center;
      min-height: 100vh;
      margin: 2.5rem 1rem 0;
    }

    .wrapper {
      background-color: #25273c;
      border-radius: 5px;
      margin-bottom: 2rem;
    }

    .card {
      height: max-content;
      width: 100%;
      max-width: 500px;
    }

    .card__title {
      font-size: 2.5rem;
      letter-spacing: 10px;
      color: #fafafa;
    }

    .flex-container {
      display: flex;
      gap: 10px;
    }

    .flex-container-2 {
      display: flex;
      justify-content: space-between;
      gap: 5px;
    }

    .flex-container-3 {
      display: flex;
      justify-content: center;
      gap: 10px;
    }

    .flex-container-4 {
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .flex-container-5 {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .form-input-field {
      background-color: transparent;
      color: #ffffff;
      border: none;
      font-family: inherit;
      outline: none;
      width: 100%;
    }

    .form-input-field::placeholder {
      color: #ffffff;
    }

    .todo-list {
      list-style-type: none;
    }

    .todo-list__item {
      padding: 1.5em;
      border-bottom: 1px solid #4d5066;
      color: #cacde8;
    }

    .btn-round {
      min-width: 30px;
      height: 30px;
      border-radius: 50px;
      border: 1px solid #4d5066;
      background-color: #25273c;
      cursor: pointer;
    }

    .btn-round:is(.completed) {
      background: linear-gradient(rgb(87, 221, 255), rgb(192, 88, 243));
    }

    .btn-primary {
      background-color: transparent;
      border: none;
      color: #4d5066;
      font-weight: 600;
      cursor: pointer;
      transition: all 250ms ease-in-out;
    }

    .btn-primary:hover {
      color: #3a7bfd;
    }

    .btn-primary--large {
      font-size: 1.3rem;
    }

    .btn-primary--small {
      font-weight: normal;
    }

    .btn-del {
      background-color: transparent;
      border: none;
      cursor: pointer;
    }

    .completed {
      text-decoration: line-through;
    }

    .clr-white {
      color: #cacde8;
    }

    .font-bold {
      font-weight: 600;
    }

    .error-message {
      color: red;
    }

    .mb-1 {
      margin-bottom: 1rem;
    }

    .p-1 {
      padding: 1.5em;
    }
  </style>

  <body>
    <div class="container">
      <div class="card">
        <div class="flex-container-4 mb-1">
          <h2 class="card__title">TODO</h2>
          <p class="error-message">{{ todo_error_message }}</p>
        </div>

        <form class="wrapper flex-container p-1" action="{% url 'todo:create-todo' user.id %}" method="post">
          {% csrf_token %}
          <button class="btn-round" type="submit"></button>
          <input
            class="form-input-field"
            type="text"
            name="todoText"
            id="todoText"
            placeholder="Create a new todo..."
            required
            autofocus
          />
        </form>

        <div class="wrapper">
          <ul class="todo-list">
            {% for todo in todo_list %}
            <li class="todo-list__item flex-container-5">
              <div class="flex-container-4">
                <a href="{% url 'todo:completed' user.id todo.id %}">
                  <button class="btn-round {% if todo.is_completed %} completed {% endif %}"></button>
                </a>
                <span {% if todo.is_completed %} class="completed" {% endif %}>{{ todo.text }}</span>
              </div>
              <a href="{% url 'todo:delete-task' user.id todo.id %}">
                <button class="btn-del">
                  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18">
                    <path
                      fill="#494C6B"
                      fill-rule="evenodd"
                      d="M16.97 0l.708.707L9.546 8.84l8.132 8.132-.707.707-8.132-8.132-8.132 8.132L0 16.97l8.132-8.132L0 .707.707 0 8.84 8.132 16.971 0z"
                    />
                  </svg>
                </button>
              </a>
            </li>
            {% endfor %}
          </ul>

          <div class="flex-container-2 p-1">
            <p class="clr-white font-bold">{{ uncompleted_task }} uncompleted task{{ uncompleted_task|pluralize }}</p>
            <a href="{% url 'todo:delete-completed' user.id %}">
              <button class="btn-primary btn-primary--small">Clear Completed</button>
            </a>
          </div>
        </div>

        <div class="wrapper flex-container-3 p-1">
          <a href="{% url 'todo:home' user.id %}">
            <button class="btn-primary btn-primary--large">All</button>
          </a>
          <a href="{% url 'todo:filter' user.id 'active' %}">
            <button class="btn-primary btn-primary--large">Active</button>
          </a>
          <a href="{% url 'todo:filter' user.id 'completed' %}">
            <button class="btn-primary btn-primary--large">Completed</button>
          </a>
        </div>
      </div>
    </div>
  </body>
</html>

templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo</title>

    <style>
      * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
      }

      .container {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
      }

      .card {
        padding: 1.5em;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.142);
        border-radius: 10px;
        margin: 0 1rem;
        width: 100%;
        max-width: 400px;
      }

      .card__title {
        text-align: center;
        margin-bottom: 1rem;
      }

      .form-label {
        font-size: 1.2rem;
        font-weight: 600;
        margin-bottom: 0.2rem;
        display: block;
      }

      .form-input-field {
        width: 100%;
        height: 30px;
        padding: 0 0.5em;
        font-size: 1.2rem;
      }

      .btn-login {
        background-color: #25273c;
        color: white;
        font-weight: 600;
        width: 100%;
        font-size: 1.5rem;
        padding: 0.5em;
        border: 1px solid #25273c;
        border-radius: 5px;
        cursor: pointer;
      }

      .btn-create {
        background-color: #3a7bfd;
        color: white;
        text-align: center;
        display: inline-block;
        text-decoration: none;
        padding: 0.5em 1em;
        margin-top: 1rem;
        font-size: 1.3rem;
        font-weight: 600;
        color: #ffffff;
        border-radius: 5px;
        border: none;
      }

      .text-center {
        text-align: center;
      }

      .mb-1 {
        margin-bottom: 1rem;
      }

      .text-red {
        color: #ff0000;
        margin-top: 0.5rem;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="card">
        {% if to_create_account %}
        <h1 class="card__title">Create Account</h1>
        {% endif %}

        <form {% if to_create_account %} action="{% url 'todo:save-account' %}" {% else %} action="" {% endif %} method="post">
          {% csrf_token %}
          <div class="mb-1">
            <label class="form-label" for="username">Username</label>
            <input class="form-input-field" type="text" name="username" id="username" value="{{ username }}" required />
            <div class="text-red">{{ username_error_message }}</div>
          </div>
          <div>
            <label class="form-label" for="password">Password</label>
            <input class="form-input-field" type="password" name="password" id="password" value="{{ password }}" required />
          </div>

          {% if to_create_account %}
          <button class="btn-create" type="submit">Create Account</button>
          {% else %}
          <button class="btn-login" type="submit">Log-in</button>
          {% endif %}
        </form>

        <div class="text-center">
          {% if to_create_account %} {% else %}
          <a class="btn-create" href="{% url 'todo:create-account' %}">Create new account</a>
          {% endif %}
        </div>
      </div>
    </div>
  </body>
</html>